{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "ef4ece11-ed0d-43e1-a0d0-74adee53fd1c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.\n"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "from keras.models import load_model\n",
    "from pygame import mixer\n",
    "import time\n",
    "from datetime import datetime\n",
    "\n",
    "# Load model\n",
    "model = load_model(\"drowsy_model_final.h5\")\n",
    "labels = ['Closed', 'Open']\n",
    "\n",
    "# Initialize sound alert\n",
    "mixer.init()\n",
    "mixer.music.load(\"alert.wav\")\n",
    "\n",
    "# Haar cascades\n",
    "face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_alt.xml')\n",
    "left_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_lefteye_2splits.xml')\n",
    "right_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_righteye_2splits.xml')\n",
    "\n",
    "# Video capture\n",
    "cap = cv2.VideoCapture(0)\n",
    "cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)\n",
    "cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)\n",
    "cv2.namedWindow(\"Drowsiness Detection\", cv2.WINDOW_NORMAL)\n",
    "cv2.moveWindow(\"Drowsiness Detection\", 300, 150)\n",
    "\n",
    "# Video writer\n",
    "frame_width = int(cap.get(3))\n",
    "frame_height = int(cap.get(4))\n",
    "fourcc = cv2.VideoWriter_fourcc(*'XVID')\n",
    "out = cv2.VideoWriter('drowsiness_output.avi', fourcc, 20.0, (frame_width, frame_height))\n",
    "\n",
    "# Trackers\n",
    "score = 0\n",
    "start_time = None\n",
    "\n",
    "def predict_eye(eye_img):\n",
    "    eye_img = cv2.resize(eye_img, (64, 64))\n",
    "    eye_img = cv2.cvtColor(eye_img, cv2.COLOR_GRAY2RGB)\n",
    "    eye_img = eye_img.astype(\"float32\") / 255.0\n",
    "    eye_img = np.expand_dims(eye_img, axis=0)\n",
    "    pred = model.predict(eye_img, verbose=0)\n",
    "    return labels[np.argmax(pred)]\n",
    "\n",
    "while True:\n",
    "    ret, frame = cap.read()\n",
    "    if not ret:\n",
    "        break\n",
    "\n",
    "    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)\n",
    "    faces = face_cascade.detectMultiScale(gray, 1.3, 5)\n",
    "    left_status = right_status = 'Open'\n",
    "\n",
    "    for (x, y, w, h) in faces:\n",
    "        cv2.rectangle(frame, (x, y), (x+w, y+h), (90, 90, 90), 2)\n",
    "        break\n",
    "\n",
    "    left_eye = left_cascade.detectMultiScale(gray)\n",
    "    for (x, y, w, h) in left_eye:\n",
    "        roi = gray[y:y+h, x:x+w]\n",
    "        left_status = predict_eye(roi)\n",
    "        break\n",
    "\n",
    "    right_eye = right_cascade.detectMultiScale(gray)\n",
    "    for (x, y, w, h) in right_eye:\n",
    "        roi = gray[y:y+h, x:x+w]\n",
    "        right_status = predict_eye(roi)\n",
    "        break\n",
    "\n",
    "    eye_status = f\"L: {left_status} | R: {right_status}\"\n",
    "\n",
    "    # Score logic\n",
    "    if left_status == 'Closed' and right_status == 'Closed':\n",
    "        score += 1\n",
    "        if start_time is None:\n",
    "            start_time = time.time()\n",
    "        elif time.time() - start_time >= 3:\n",
    "            if not mixer.music.get_busy():\n",
    "                mixer.music.play()\n",
    "            cv2.putText(frame, \"DROWSINESS ALERT!\", (100, 100),\n",
    "                        cv2.FONT_HERSHEY_SIMPLEX, 1.2, (0, 0, 0), 3)\n",
    "    else:\n",
    "        start_time = None\n",
    "        mixer.music.stop()\n",
    "        score = max(score - 1, 0)\n",
    "\n",
    "    # Timestamp (top-right)\n",
    "    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n",
    "    cv2.putText(frame, timestamp, (frame.shape[1] - 240, 30),\n",
    "                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 0), 2)\n",
    "\n",
    "    # Eye Status (bottom-left in blue)\n",
    "    cv2.putText(frame, f\"Eye Status: {eye_status}\",\n",
    "                (20, frame.shape[0] - 40),\n",
    "                cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 100, 0), 2)\n",
    "\n",
    "    # Score (bottom-left below status, in green)\n",
    "    cv2.putText(frame, f\"Drowsiness Score: {score}\",\n",
    "                (20, frame.shape[0] - 10),\n",
    "                cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 150, 0), 2)\n",
    "\n",
    "    # Show and save video\n",
    "    cv2.imshow(\"Drowsiness Detection\", frame)\n",
    "    out.write(frame)\n",
    "\n",
    "    if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "        break\n",
    "\n",
    "# Cleanup\n",
    "cap.release()\n",
    "out.release()\n",
    "cv2.destroyAllWindows()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bf401d18-e36f-4ed9-8a5d-339c845236ba",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a84ed85d-2f4d-4fde-9c53-f55370eaac1c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (TensorFlow)",
   "language": "python",
   "name": "my-tf-kernel"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
